run:
  tests: false
  skip-dirs:
    - mongo-migration
    - docs
    - bin
  modules-download-mode: readonly

output:
  print-issued-lines: false
  uniq-by-line: false
  sort-results: true

linters-settings:
    gomoddirectives:
      replace-local: true

    nlreturn:
      block-size: 5

    varnamelen:
      max-distance: 5
      min-name-length: 2

linters:
  enable-all: true
  disable:
    - interfacer # deprecated (since v1.38.0): Archived.
    - golint     # deprecated (since v1.41.0): Archived. Replaced by revive.
    - scopelint  # deprecated (since v1.39.0): Deprecated. Replaced by exportloopref.
    - maligned   # deprecated (since v1.38.0): Archived. Replaced by govet 'fieldalignment'.
    - gofumpt
    - gci
    - goerr113
    - forbidigo
    - depguard
    - exhaustruct
    - exhaustivestruct
    - nonamedreturns
    - tagliatelle
    - wrapcheck
    - wsl

issues:
  max-same-issues: 0
