version: '3'

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: "globalhitss"
      DATABASE_USER: "postgres"
      POSTGRES_PASSWORD: "password123"
    ports:
      - "5432:5432"
    expose:
      - "5432"